### ISSUE TITLE
Feature activation

### ISSUE THREAD

**Issue by abdosaeedelhassan** [laravel/pennant#39]
Firstly thank you for a good package, i hope that in future be implemented inside laravel framework.
when creating new future without filter scope like next 
`
 Feature::define('administrator','administrator');
`
that create feature is active by default for all users, when i checked like next
`
 Feature::active('administrator')
`
will give me (true), i suggest that the process be like next:
`
 Feature::active('administrator'); // will be false
 Feature::activate('administrator'); // activate for current user
 Feature::active('administrator'); // will be true
`
This will give us ability to use this package also as roles and permissions.

Thanks.

**Comment by timacdonald** [comment]
Hey @abdosaeedelhassan,

When you create a feature definition:

```php
Feature::define('administrator', 'administrator');
```

You are specifying that the default _value_ of the `administrator` flag should be the string `"administrator"`.

Note that features are not just boolean on / off, but may also contain "rich values" such as strings, arrays, etc.

For your particular usecase it sounds like you should instead do the following:

```php
Feature::define('administrator', false);
```

This will mean that everyone will have the value `false` unless you otherwise activate the feature manually.

- [Rich Value documentation](https://laravel.com/docs/10.x/pennant#rich-feature-values)

**Comment by abdosaeedelhassan** [comment]
@timacdonald  thank you for explanation, now i get it.
