### ISSUE TITLE
Conflicting behavior using in-memory vs database driver.

### ISSUE THREAD

**Issue by tomshaw** [laravel/pennant#51]
- Laravel Pennant Version: 1.2
- Laravel Version: 10.0.0
- PHP Version: 8.1.16
- Database Driver & Version: Database.

### Description:

First off excellent package I find it very useful. My application is getting conflicting results when creating features using the in-memory driver as opposed to the database driver. 

### Steps To Reproduce:

The following feature works using the in-memory driver but always returns true or false when using the database driver. The database driver requires a complete deletion of the database feature row to work correctly.

```sh
Feature::define('fast.invoice', fn (User $user) => match (true) {
    $user->isDeveloper() => true,
   default => false,
});
```

**Comment by timacdonald** [comment]
@tomshaw I believe that this is the expected behaviour.

Take the following test that **fails** on both the array and database driver: 

```php
$user = User::make(['id' => '123']);

Feature::define('fast.invoice', fn (User $user) => match (true) {
    $user->is_developer => true,
    default => false,
});

$user->is_developer = true;
$this->assertTrue(Feature::for($user)->active('fast.invoice'));

$user->is_developer = false;
$this->assertFalse(Feature::for($user)->active('fast.invoice'));
```

The last assertion will always fail.

When a value is resolved by the driver, it is "remembered".

For the database driver, that means it is saved in the database.

For the array driver, that means it is saved in an in-memory array.

On subsequent requests, the database driver will then retrieve the value from the database, not from feature definition.

The array driver, however, cannot do this as the value is cleared out of memory on each request.

If you feel I've missed something, please let me know.

**Comment by tomshaw** [comment]
I'm currently using roles/user-role pivot table. When I add the user.id role.id to the pivot table, the user object returns true/false accordingly. One solution is to empty the table when updating the user/role in the admin/update route? It's such a minimal footprint I'm currently relying on the in memory store. Thanks :)

**Comment by tomshaw** [comment]
Fudge. Just tested a fresh install and same differing driver results. The database driver persists the user state and shouldn't.
