### ISSUE TITLE
Use a different driver per feature

### ISSUE THREAD

**Issue by iagobruno** [laravel/pennant#54]
## Proposal

Allowing a feature to use a driver other than the default defined in the `config/pennant.php`.

For example, I defined that I want to use the database driver in the config file.

```php
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Pennant Store
    |--------------------------------------------------------------------------
    | Supported: "array", "database"
    */
    'default' => env('PENNANT_STORE', 'database'),
    ...
```

So I want a specific feature to use the array driver to always check if the user is subscribed to a plan:

```php
Feature::driver('array')->define('edit-tweet', function (User $user) {
    return $user->subscribed('premium-plan');
});
```

On class based feature:

```php
namespace App\Features;
 
class EditTweetFeature
{
    /**
     * The driver that should be used to store the state for this specific feature.
     */
    public $driver = 'array';

    /**
     * Resolve the feature's initial value.
     */
    public function resolve(User $user): mixed
    {
        return $user->subscribed('premium-plan');
    }
}
```

Or even when programmatically activating a feature:

```php
Feature::driver('redis')->activate('edit-tweet');
```

This is just a proposal. Comments and suggestions are welcome.

**Comment by ahmedash95** [comment]
Hey @iagobruno, from Taylor's comment [here](https://github.com/laravel/pennant/pull/53#issuecomment-1464930571). 

what you need is just to use `store` instead of `driver`

```php
Feature::store('redis')->activate('edit-tweet');
```

**Comment by driesvints** [comment]
Thanks @ahmedash95

**Comment by cosmastech** [comment]
I realized this was closed quite a while ago, but I would like to chime in that I think this would be incredibly helpful. Or even allow searching through multiple drivers.

For instance, on a current project, we are trying to reduce worker costs by using a Lambda function for retrieving large files.

```php
Feature::driver('array')
    ->define(
        'use-lambda-for-fetch',
        fn () => config('something.bool') && config('filesystems.default') === 's3'
    );
```

Now every time we check this feature, we have to make sure we have explicitly call `Feature::driver('array')`. Say explicitly setting the driver is missed during a code review

```php
use Feature;

public function getContents(string $url)
{
    if (Feature::active('use-lambda-for-fetch')) {
        return callMyLambdaFunction($url);
    }
    
    return file_get_contents($url);
}
```

Now the cost-saving lambda fetch function is never called and it's a bit of a pain to track down why it's not happening. Nothing is written to the database (as we would expect if it were using the `array` driver), and only if we have been very diligent in writing logs would we catch it.

It also requires having to write down the driver every where we need to use it. Say we decide we want to switch this from an app level feature flag to a user level feature (like we don't want to interrupt the experience of our most important customers while we tweak the Lambda)... we have to track down every where that we have called this feature to change the driver.

A solution I came up for this is to create a FeatureEnum that does all the heavy lifting.

```php
namespace App\Enums;

enum FeatureEnum: string
{
    case UseLambdaForFetch = 'use-lambda-for-fetch';

    public function getDriver(): Decorator
    {
        $driverName = match ($this) {
            self::UseLambdaForFetch => 'array',
            default => null,
        };

        return Feature::driver($driverName);
    }

    public function isActive(): bool
    {
        return $this->getDriver()->active($this->value);
    }

    public static function defineAllFeatures(): void
    {
        self::UseLambdaForFetch->getDriver()->define(
            fn () => config('something.bool') && config('filesystems.default') === 's3'
        );
    }
}
```

Now we can call `App\Enums\FeatureEnum::defineAllFeatures()` in our app service provider and our function would become:

```php
use App\Enums\FeatureEnum;

public function getContents(string $url)
{
    if (FeatureEnum::UseLambdaForFetch->isActive()) {
        return callMyLambdaFunction($url);
    }
    
    return file_get_contents($url);
}
```

But I'll be honest... this seems like a lot of work to get around the problem. It's not the native Laravel way, so we need to document this functionality for new developers, and again, it's easy to miss in a code review that someone is just checking against Pennant's Feature facade rather than our app built `FeatureEnum`

Sharing here as others have clearly bumped up against this. Would love to see this incorporated into the package itself.

**Comment by timacdonald** [comment]
In regards to using the wrong driver and having trouble tracking things down, I would recommend doing the following in a service provider...

```php
use Laravel\Pennant\Events\UnknownFeatureResolved;

Event::listen(function (UnknownFeatureResolved $event) {
    report("Resolving unknown feature [{$event->feature}].");
});
```

When it comes to having a feature define what driver to be resolved from, I would probably just do it the other way and build a custom driver that finds the feature from a set of drivers.

Use this as the default driver and register the features against specific drivers in a service provider.

```php
<?php

namespace Laravel\Pennant\Drivers;

use Laravel\Pennant\Contracts\Driver;
use Illuminate\Support\Collection;
use RuntimeException;

class MultiDriver implements Driver
{
    public function __construct(protected Collection $drivers)
    {
        //
    }

    /**
     * Define an initial feature flag state resolver.
     *
     * @param  (callable(mixed $scope): mixed)  $resolver
     */
    public function define(string $feature, callable $resolver)
    {
        throw new RuntimeException('You should define features against specific drivers.');
    }

    /**
     * Retrieve the names of all defined features.
     *
     * @return array<string>
     */
    public function defined(): array
    {
        return $this->drivers->flatMap->defined()->all();
    }

    /**
     * Get multiple feature flag values.
     *
     * @param  array<string, array<int, mixed>>  $features
     * @return array<string, array<int, mixed>>
     */
    public function getAll(array $features): array
    {
        // TODO need more coffee before I implement this one.
    }

    /**
     * Retrieve a feature flag's value.
     */
    public function get(string $feature, mixed $scope): mixed
    {
        return $this->drivers
            ->first(fn (Driver $driver) => array_key_exists($feature, $driver->defined()))
            ->get($feature, $scope);
    }

    /**
     * Set a feature flag's value.
     */
    public function set(string $feature, mixed $scope, mixed $value): void
    {
        $this->drivers
            ->first(fn (Driver $driver) => array_key_exists($feature, $driver->defined()))
            ->set($feature, $scope, $value);
    }

    /**
     * Set a feature flag's value for all scopes.
     */
    public function setForAllScopes(string $feature, mixed $value): void
    {
        $this->drivers
            ->first(fn (Driver $driver) => array_key_exists($feature, $driver->defined()))
            ->setForAllScopes($feature, $value);
    }

    /**
     * Delete a feature flag's value.
     */
    public function delete(string $feature, mixed $scope): void
    {
        $this->drivers
            ->first(fn (Driver $driver) => array_key_exists($feature, $driver->defined()))
            ->delete($feature, $scope);
    }

    /**
     * Purge the given features from storage.
     */
    public function purge(?array $features): void
    {
        collect($this->drivers)->each->purge($features);
    }
}
```



Hope this helps.
